name: Build Android Production
on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build App Bundle (.aab)
        id: build
        run: |
          npx eas-cli build --platform android --profile production --local --non-interactive --output=./app-release.aab
        env:
          EAS_NO_VCS: 1

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle
          path: ./app-release.aab
